### ISSUE TITLE
parser argument --num-cpu is a typo

### ISSUE THREAD

**Issue by eduand-alvarez** [oneapi-src/predictive-health-analytics#3]
In the python module named train_predict_pam.py, the parser argument for selecting the number of threads is misspelled. 

Current: 

parser.add_argument('-ncpu',
                        '--num-cpu',
                        type=int,
                        required=True,
                        default=4,
                        help='Number of cpu cores: \
                            xgboost v0.81 does not use nthread as number of cores,\
                            hence need to align that explicitly using this parameter')

What it should be to match rest of code: 

parser.add_argument('-ncpu',
                        '--num_cpu',
                        type=int,
                        required=True,
                        default=4,
                        help='Number of cpu cores: \
                            xgboost v0.81 does not use nthread as number of cores,\
                            hence need to align that explicitly using this parameter')

**Comment by rbernalc** [comment]
Thanks for the comment. Reference kit has been updated.
