### ISSUE TITLE
This phrase does not make sense 

### ISSUE THREAD

**Issue by eduand-alvarez** [oneapi-src/predictive-health-analytics#5]
"With Intel® enhancements in this machine learning model and daal4py framework, we do not need to go with higher cost MLOps environment as it provides huge gain even on the CPU based hardware." 

MLOps is not a counterpoint to using these tools or frameworks. MLOps is an operational paradigm for ML/AI applications for deployment and streamlining the ML Lifecycle.

**Comment by rbernalc** [comment]
Thanks for the comment. This phrase is not present anymore in the updated version of the kit.
